### ISSUE TITLE
Feature request: FAMD and reconst

### ISSUE THREAD

**Issue by nikosGeography** [husson/FactoMineR#30]
Hi, I was wondering if it makes sense to add the possibility to reconsttuct original observations after using the FAMD() function on a dataset containing both continuous and categorical (integer) values. An example of categorical value would be obesity levels. Is this something that its plausible or not? If not, feel free to close the issue.

**Comment by husson** [comment]
It is not really interesting because categorical variables can only be reconstructed with categories.
